server:
    port: 8082
#debug: true
logging:
    level:
        com.rxx: debug
    pattern:
        console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"
        file: "%d{yyyy-MM-dd} == [%thread] == %-5level == %logger{50} - %msg%n"
    path: /Users/renxiaoxing/Documents/gitRepo/CoffeeJourney/log/

